export const EMOJIS = {
  SMILING_FACE: '😊',
  THUMBS_UP: '👍',
  THUMBS_DOWN: '👎',
  RAISED_HAND_WITH_FINGERS_SPLAYED: '🖐️',
  CALENDAR: '📅',
  NOTEBOOK: '📓',
  BOOKMARK: '🔖',
  PUSH_PIN: '📌',
  LOCK: '🔒',
  UNLOCK: '🔓',
  HOURGLASS: '⏳',
  STOPWATCH: '⏱️',
  TIMER_CLOCK: '⏰',
  WARNNING: '⚠️',
  NO_ENTRY: '⛔',
  PROHIBITED: '🚫',
  SUCCESS: '✅',
  CHECK_MARK: '✔️',
  INFO: 'ℹ️',
};
